worlds:
  world_islandcraft:
    island-size: 288
    ocean-size: 32
    inter-island-biome: DEEP_OCEAN
    islands:
      birch-forest:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: BIRCH_FOREST
        mountains: BIRCH_FOREST_MOUNTAINS
        hills: BIRCH_FOREST_HILLS
        hills-mountains: BIRCH_FOREST_HILLS_MOUNTAINS
        forest: ~
        forest-mountains: ~
      cold-taiga:
        outer-coast: OCEAN
        inner-coast: COLD_BEACH
        normal: COLD_TAIGA
        mountains: COLD_TAIGA_MOUNTAINS
        hills: COLD_TAIGA_HILLS
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
      desert:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: DESERT
        mountains: DESERT_MOUNTAINS
        hills: DESERT_HILLS
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
      extreme-hills:
        outer-coast: OCEAN
        inner-coast: STONE_BEACH
        normal: EXTREME_HILLS
        mountains: EXTREME_HILLS_MOUNTAINS
        hills: EXTREME_HILLS_PLUS
        hills-mountains: EXTREME_HILLS_PLUS_MOUNTAINS
        forest: SMALL_MOUNTAINS
        forest-mountains: ~
      forest:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: FOREST
        mountains: ~
        hills: FOREST_HILLS
        hills-mountains: ~
        forest: FLOWER_FOREST
        forest-mountains: ~
      ice-plains:
        outer-coast: OCEAN
        inner-coast: FROZEN_OCEAN
        normal: ICE_PLAINS
        mountains: ~
        hills: ICE_MOUNTAINS
        hills-mountains: ~
        forest: ICE_PLAINS_SPIKES
        forest-mountains: ~
      jungle:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: JUNGLE
        mountains: JUNGLE_MOUNTAINS
        hills: JUNGLE_HILLS
        hills-mountains: ~
        forest: JUNGLE_EDGE
        forest-mountains: JUNGLE_EDGE_MOUNTAINS
      mega-taiga:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: MEGA_TAIGA
        mountains: MEGA_SPRUCE_TAIGA
        hills: MEGA_TAIGA_HILLS
        hills-mountains: MEGA_SPRUCE_TAIGA_HILLS
        forest: ~
        forest-mountains: ~
      mesa:
        outer-coast: OCEAN
        inner-coast: MESA
        normal: MESA
        mountains: MESA_BRYCE
        hills: MESA_PLATEAU
        hills-mountains: MESA_PLATEAU_MOUNTAINS
        forest: MESA_PLATEAU_FOREST
        forest-mountains: MESA_PLATEAU_FOREST_MOUNTAINS
      mushroom-island:
        outer-coast: OCEAN
        inner-coast: MUSHROOM_SHORE
        normal: MUSHROOM_ISLAND
        mountains: ~
        hills: ~
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
      plains:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: PLAINS
        mountains: ~
        hills: SUNFLOWER_PLAINS
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
      roofed-forest:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: ROOFED_FOREST
        mountains: ROOFED_FOREST_MOUNTAINS
        hills: ~
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
      savana:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: SAVANNA
        mountains: SAVANNA_MOUNTAINS
        hills: SAVANNA_PLATEAU
        hills-mountains: SAVANNA_PLATEAU_MOUNTAINS
        forest: ~
        forest-mountains: ~
      swampland:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: SWAMPLAND
        mountains: SWAMPLAND_MOUNTAINS
        hills: ~
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
      taiga:
        outer-coast: OCEAN
        inner-coast: BEACH
        normal: TAIGA
        mountains: TAIGA_MOUNTAINS
        hills: TAIGA_HILLS
        hills-mountains: ~
        forest: ~
        forest-mountains: ~
