name: IslandCraft-Core
version: 0.0.3
description: Needed for most IslandCraft plugins
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.core.IslandCraft

