name: IslandCraft-WorldGenerator
version: 0.0.2
description: Generates an ocean with islands
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.worldgenerator.WorldGeneratorPlugin
load: STARTUP
depend: [IslandCraft-CustomWorldChunkManager]
