local-chat-radius: 128
purchase-cost-item: Diamond
purchase-cost-amount: 1
purchase-cost-increase: 1
tax-cost-item: Diamond
tax-cost-amount: 1
tax-cost-increase: 1
max-islands-per-player: 7
worlds:
  world:
    island-size-chunks: 16
    island-gap-chunks: 4
    resource-island-rarity: 20
    ocean-biome: Ocean
    biomes:
      Forest Island:
        normal: Forest
        detail: ForestHills
        border: Beach
        rarity: 100
      Desert Island:
        normal: Desert
        detail: DesertHills
        border: Beach
        rarity: 100
      Taiga Island:
        normal: Taiga
        detail: TaigaHills
        border: Beach
        rarity: 100
      Jungle Island:
        normal: Jungle
        detail: JungleHills
        border: Beach
        rarity: 100
      Extreme Hills Island:
        normal: Extreme Hills
        detail: Extreme Hills
        border: Extreme Hills Edge
        rarity: 100
      Swamp Island:
        normal: Swampland
        detail: Swampland
        border: Swampland
        rarity: 100
      Plains Island:
        normal: Plains
        detail: Plains
        border: Beach
        rarity: 100
      Ice Plains Island:
        normal: Ice Plains
        detail: Ice Mountains
        border: Ice Plains
        rarity: 100
      Mushroom Island:
        normal: MushroomIsland
        detail: MushroomIsland
        border: MushroomIslandShore
        rarity: 1
