name: IslandCraft
version: 0.0.2
description: This plugin modifies the terrain generation to create an ocean with many islands, each of a single biome.
load: STARTUP
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.bukkit.IslandCraftPlugin
database: true
depend: [TerrainControl, WorldEdit, WorldGuard]
commands:
  island:
    description: Commands for managing islands
    permission: islandcraft.command.island
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> purchase - Purchase an island
      /<command> abandon - Abandon an island
      /<command> examine - List information about an island
      /<command> rename - Give a new name to an island
      /<command> tax - Pay tax for an island
  island purchase:
    description: Purchase the island you are standing on
    permission: islandcraft.command.island.purchase
    usage: /<command>
  island abandon:
    description: Abandon the island you are standing on
    permission: islandcraft.command.island.abandon
    usage: /<command>
  island tax:
    description: Pay 500 days tax for the island you are standing on
    permission: islandcraft.command.island.tax
    usage: /<command>
  island examine:
    description: List information about the island you are standing on
    permission: islandcraft.command.island.examine
    usage: /<command>
  island rename:
    description: Give a new name to the island you are standing on (used in greeting and farewell messages)
    permission: islandcraft.command.island.rename
    usage: /<command> <name...>
  warp:
    description: Warp to a random available island
    permission: islandcraft.command.warp
    usage: /<command>
  waypoint:
    description: Commands to manage your compass waypoints
    permission: islandcraft.command.waypoint
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> add - Add a waypoint at your current location
      /<command> remove - Remove a waypoint
      /<command> list - List your waypoints
      /<command> set - Make your compass point towards a waypoint
  waypoint add:
    description: Add a waypoint at your current location
    permission: islandcraft.command.waypoint.add
    usage: /<command> <waypoint...>
  waypoint remove:
    description: Remove a waypoint
    permission: islandcraft.command.waypoint.remove
    usage: /<command> <waypoint...>
  waypoint list:
    description: List your waypoints
    permission: islandcraft.command.waypoint.list
    usage: /<command>
  waypoint set:
    description: Make your compass point towards a waypoint
    permission: islandcraft.command.waypoint.set
    usage: /<command> <waypoint...>
  icsudo:
    description: Dangerous commands for IslandCraft
    permission: islandcraft.command.icsudo
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> regenerate - Completely regenerate a whole island
      /<command> reserved - Set an island to be a reserved island
      /<command> resource - Set an island to be a resource island
      /<command> available - Set an island to be an available island
      /<command> purchase - Purchase an island for another player without charge
      /<command> rename - Rename an island you do not own
  icsudo regenerate:
    description: |
      Completely regenerate the island you are standing on and the surrounding ocean
      New randomly selected biome and shape
      Everything will be destroyed
      You have been warned!
    permission: islandcraft.command.icsudo.regenerate
    usage: /<command>
  icsudo reserved:
    description: |
      Set the island you are standing on to be a reserved island
      No player have any permission to build on a reserved island
    permission: islandcraft.command.icsudo.reserved
    usage: /<command>
  icsudo resource:
    description: |
      Set the island you are standing on to be a resource island
      All players have permission to build on a resource island
    permission: islandcraft.command.icsudo.resource
    usage: /<command>
  icsudo available:
    description: |
      Set the island you are standing on to be a available island
      Players may purchase available islands
    permission: islandcraft.command.icsudo.available
    usage: /<command>
  icsudo purchase:
    description: Purchase the island you are standing on for another player without charge
    permission: islandcraft.command.icsudo.purchase
    usage: /<command> <player>
  icsudo rename:
    description: Rename the island you are standing on even if you do not own it
    permission: islandcraft.command.icsudo.rename
    usage: /<command> <name...>
permissions:
  islandcraft.command.island:
    default: true
    children:
      islandcraft.command.island.purchase: true
      islandcraft.command.island.abandon: true
      islandcraft.command.island.tax: true
      islandcraft.command.island.examine: true
      islandcraft.command.island.rename: true
  islandcraft.command.warp:
    default: op
  islandcraft.command.waypoint:
    default: true
    children:
      islandcraft.command.waypoint.add: true
      islandcraft.command.waypoint.remove: true
      islandcraft.command.waypoint.list: true
      islandcraft.command.waypoint.set: true
  islandcraft.command.icsudo:
    default: op
    children:
      islandcraft.command.icsudo.regenerate: true
      islandcraft.command.icsudo.reserved: true
      islandcraft.command.icsudo.resource: true
      islandcraft.command.icsudo.available: true
      islandcraft.command.icsudo.purchase: true
      islandcraft.command.icsudo.rename: true
