name: IslandCraft
version: 0.0.2
description: This plugin modifies the terrain generation to create an ocean with many islands, each of a single biome.
load: STARTUP
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.bukkit.IslandCraftPlugin
database: true
depend: [TerrainControl, WorldEdit, WorldGuard]
commands:
  warp:
    description: Warp to a random available island
    permission: islandcraft.command.warp
    usage: /<command>
  icsudo:
    description: Dangerous commands for IslandCraft
    permission: islandcraft.command.icsudo
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> regenerate - Completely regenerate a whole island
      /<command> reserved - Set an island to be a reserved island
      /<command> resource - Set an island to be a resource island
      /<command> available - Set an island to be an available island
      /<command> purchase - Purchase an island for another player without charge
      /<command> rename - Rename an island you do not own
  icsudo regenerate:
    description: |
      Completely regenerate the island you are standing on and the surrounding ocean
      New randomly selected biome and shape
      Everything will be destroyed
      You have been warned!
    permission: islandcraft.command.icsudo.regenerate
    usage: /<command>
  icsudo reserved:
    description: |
      Set the island you are standing on to be a reserved island
      No player have any permission to build on a reserved island
    permission: islandcraft.command.icsudo.reserved
    usage: /<command>
  icsudo resource:
    description: |
      Set the island you are standing on to be a resource island
      All players have permission to build on a resource island
    permission: islandcraft.command.icsudo.resource
    usage: /<command>
  icsudo available:
    description: |
      Set the island you are standing on to be a available island
      Players may purchase available islands
    permission: islandcraft.command.icsudo.available
    usage: /<command>
  icsudo purchase:
    description: Purchase the island you are standing on for another player without charge
    permission: islandcraft.command.icsudo.purchase
    usage: /<command> <player>
  icsudo rename:
    description: Rename the island you are standing on even if you do not own it
    permission: islandcraft.command.icsudo.rename
    usage: /<command> <name...>
permissions:
  islandcraft.command.warp:
    default: op
  islandcraft.command.icsudo:
    default: op
    children:
      islandcraft.command.icsudo.regenerate: true
      islandcraft.command.icsudo.reserved: true
      islandcraft.command.icsudo.resource: true
      islandcraft.command.icsudo.available: true
      islandcraft.command.icsudo.purchase: true
      islandcraft.command.icsudo.rename: true
