name: IslandCraft-PartyChat
version: 0.0.3
description: Allows players to join parties to chat to each other
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.partychat.PartyChatPlugin
database: true
commands:
  p:
    description: Send a message to members of your party
    permission: islandcraft.command.p
    usage: "\u00a7c/<command> <message...>"
  party:
    description: Commands to manage your party
    permission: islandcraft.command.party
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> join - Join a party
      /<command> leave - Leave your party
      /<command> members - List the members of your party
  party join:
    description: Join a party
    permission: islandcraft.command.party.join
    usage: "\u00a7cUsage: /<command> <party...>"
  party leave:
    description: Leave your party
    permission: islandcraft.command.party.leave
    usage: "\u00a7cUsage: /<command>"
  party members:
    description: List the members of your party
    permission: islandcraft.command.party.members
    usage: "\u00a7cUsage: /<command>"
permissions:
  islandcraft.command.p:
    default: true
  islandcraft.command.party:
    default: true
    children:
      islandcraft.command.party.join: true
      islandcraft.command.party.leave: true
      islandcraft.command.party.members: true
