purchase-cost-item: DIAMOND
purchase-cost-amount: 1
purchase-cost-increase: 1
tax-cost-item: DIAMOND
tax-cost-amount: 1
tax-cost-increase: 1
tax-days-initial: 500
tax-days-increase: 500
tax-days-max: 2000
max-islands-per-player: 7
worlds:
  world:
    island-size: 288
    island-separation: 320
    resource-island-rarity: 0.25
