purchase-cost-item: DIAMOND
purchase-cost-amount: 1
purchase-cost-increase: 1
tax-cost-item: DIAMOND
tax-cost-amount: 1
tax-cost-increase: 1
tax-days-initial: 500
tax-days-increase: 500
tax-days-max: 2000
max-islands-per-player: 7
worlds:
  world:
    island-size: 288
    island-separation: 320
    resource-island-rarity: 0.25
message:
  island-examine-resource: |
    §7[-] You are on a §aResource§7 island:
    §7[-]   Title: §a%s
    §7[-]   World: §a%s
    §7[-]   X: §a%s
    §7[-]   Z: §a%s
  island-examine-reserved: |
    §7[-] You are on a §aReserved§7 island:
    §7[-]   Title: §a%s
    §7[-]   World: §a%s
    §7[-]   X: §a%s
    §7[-]   Z: §a%s
  island-examine-new: |
    §7[-] You are on a §aNew§7 island:
    §7[-]   Title: §a%s
    §7[-]   World: §a%s
    §7[-]   X: §a%s
    §7[-]   Z: §a%s
  island-examine-abandoned: |
    §7[-] You are on an §aAbandoned§7 island:
    §7[-]   Previous Owner: §a%s
    §7[-]   Title: §a%s
    §7[-]   World: §a%s
    §7[-]   X: §a%s
    §7[-]   Z: §a%s
  island-examine-repossessed: |
    §7[-] You are on a §aRepossessed§7 island:
    §7[-]   Previous Owner: §a%s
    §7[-]   Title: §a%s
    §7[-]   World: §a%s
    §7[-]   X: §a%s
    §7[-]   Z: §a%s
  island-examine-private: |
    §7[-] You are on a §aPrivate§7 island:
    §7[-]   Owner: §a%s
    §7[-]   Title: §a%s
    §7[-]   Tax paid: §a%s
    §7[-]   World: §a%s
    §7[-]   X: §a%s
    §7[-]   Z: §a%s
