name: IslandCraft-RealEstate
version: 0.0.2
description: Allows players to purchase islands
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.realestate.RealEstatePlugin
database: true
commands:
  island:
    description: Commands for managing islands
    permission: islandcraft.command.island
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> purchase - Purchase an island
      /<command> abandon - Abandon an island
      /<command> examine - List information about an island
      /<command> rename - Give a new name to an island
      /<command> tax - Pay tax for an island
  island purchase:
    description: Purchase the island you are standing on
    permission: islandcraft.command.island.purchase
    usage: /<command>
  island abandon:
    description: Abandon the island you are standing on
    permission: islandcraft.command.island.abandon
    usage: /<command>
  island tax:
    description: Pay 500 days tax for the island you are standing on
    permission: islandcraft.command.island.tax
    usage: /<command>
  island examine:
    description: List information about the island you are standing on
    permission: islandcraft.command.island.examine
    usage: /<command>
  island rename:
    description: Give a new name to the island you are standing on
    permission: islandcraft.command.island.rename
    usage: /<command> <name...>
permissions:
  islandcraft.command.island:
    default: true
    children:
      islandcraft.command.island.purchase: true
      islandcraft.command.island.abandon: true
      islandcraft.command.island.tax: true
      islandcraft.command.island.examine: true
      islandcraft.command.island.rename: true
