name: IslandCraft-RealEstate
version: 0.0.2
description: Allows players to purchase islands
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.realestate.RealEstatePlugin
load: STARTUP
database: true
commands:
  island:
    description: Commands for managing islands
    permission: islandcraft.command.island
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> purchase - Purchase an island
      /<command> abandon - Abandon an island
      /<command> examine - List information about an island
      /<command> rename - Give a new name to an island
      /<command> tax - Pay tax for an island
  island purchase:
    description: Purchase the island you are standing on
    permission: islandcraft.command.island.purchase
    usage: /<command>
  island abandon:
    description: Abandon the island you are standing on
    permission: islandcraft.command.island.abandon
    usage: /<command>
  island tax:
    description: Pay 500 days tax for the island you are standing on
    permission: islandcraft.command.island.tax
    usage: /<command>
  island examine:
    description: List information about the island you are standing on
    permission: islandcraft.command.island.examine
    usage: /<command>
  island rename:
    description: Give a new name to the island you are standing on
    permission: islandcraft.command.island.rename
    usage: /<command> <name...>
  icset:
    description: Administration commands for overriding island states
    permission: islandcraft.command.icset
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> owner - Override the owner of an island
      /<command> title - Override the title of an island
      /<command> status - Override the status of an island
      /<command> tax - Override the tax of an island
  icset owner:
    description: Override the owner of an island
    permission: islandcraft.command.icset.owner
    usage: /<command> <player>
  icset title:
    description: Override the title of an island
    permission: islandcraft.command.icset.title
    usage: /<command> <title>
  icset status:
    description: Override the status of an island
    permission: islandcraft.command.icset.status
    usage: /<command> <status>
  icset tax:
    description: Override the tax of an island
    permission: islandcraft.command.icset.tax
    usage: /<command> <tax>
permissions:
  islandcraft.command.island:
    default: true
    children:
      islandcraft.command.island.purchase: true
      islandcraft.command.island.abandon: true
      islandcraft.command.island.tax: true
      islandcraft.command.island.examine: true
      islandcraft.command.island.rename: true
  islandcraft.command.icset:
    default: op
    children:
      islandcraft.command.icset.owner: true
      islandcraft.command.icset.title: true
      islandcraft.command.icset.status: true
      islandcraft.command.icset.tax: true
