name: IslandCraft-WorldGuard
version: 0.0.3
description: Allows players to purchase islands
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.worldguard.ICWorldGuardPlugin
depend: [IslandCraft-RealEstate, WorldEdit, WorldGuard]
