name: IslandCraft-Dynmap
version: 0.0.3
description: Shows IslandCraft layer in Dynmap
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.dynmap.ICDynmapPlugin
depend: [IslandCraft-RealEstate, dynmap]
