message:
  compass: §7[-] Compass now pointing to §a%s
  compass-error: §c[-] You cannot use your compass here
  waypoint-add: §7[-] Added waypoint §a%s
  waypoint-add-world-error: §c[-] You cannot set a waypoint here
  waypoint-add-reserved-error: §c[-] You cannot override that waypoint
  waypoint-remove: §7[-] Removed waypoint §a%s
  waypoint-exists-error: §c[-] That waypoint does not exist
  waypoint-remove-error: §c[-] You cannot remove that waypoint
  waypoint-list: "§7[-] Waypoints: §a%s"
  waypoint-set-error: §7[-] Waypoint not defined
