name: IslandCraft-Compass
version: 0.0.3
description: Create waypoints which can be followed with your compass
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.compass.CompassPlugin
depend: [IslandCraft-Core]
database: true
commands:
  waypoint:
    description: Commands to manage your compass waypoints
    permission: islandcraft.command.waypoint
    usage: |
      Use /help <command> [subcommand] for more information
      /<command> add - Add a waypoint at your current location
      /<command> remove - Remove a waypoint
      /<command> list - List your waypoints
      /<command> set - Make your compass point towards a waypoint
  waypoint add:
    description: Add a waypoint at your current location
    permission: islandcraft.command.waypoint.add
    usage: /<command> <waypoint...>
  waypoint remove:
    description: Remove a waypoint
    permission: islandcraft.command.waypoint.remove
    usage: /<command> <waypoint...>
  waypoint list:
    description: List your waypoints
    permission: islandcraft.command.waypoint.list
    usage: /<command>
  waypoint set:
    description: Make your compass point towards a waypoint
    permission: islandcraft.command.waypoint.set
    usage: /<command> <waypoint...>
permissions:
  islandcraft.command.waypoint:
    default: true
    children:
      islandcraft.command.waypoint.add: true
      islandcraft.command.waypoint.remove: true
      islandcraft.command.waypoint.list: true
      islandcraft.command.waypoint.set: true
  islandcraft.compass:
    default: true
