name: IslandCraft-Suicide
version: 0.0.3
description: A more explicit command for suicide
author: hoqhuuep
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.suicide.SuicidePlugin
depend: [IslandCraft-Core]
commands:
  suicide:
    description: Kill yourself
    permission: islandcraft.command.suicide
    usage: "\u00a7cUsage: /<command>"
permissions:
  islandcraft.command.suicide:
    default: true
